Fix two lineno AttributeError causes
The following exception would be raised when checking source code
using keyword arguments:

    AttributeError: 'Node' object has no attribute 'lineno'

Only Leaf nodes have lineno and column attributes directly accessible,
we need to go through a layer of indirection to operate on any node.